-- Prevent duplicated order lines and make a complete table order update atomic.
-- This migration assumes the existing application schema where tables.id and
-- orders.table_id accept the string IDs generated by the POS (mesa_<timestamp>). 

alter table public.tables
  add column if not exists order_version bigint not null default 0;

-- Preserve the total quantity from legacy duplicate rows, then remove all but one.
with duplicate_groups as (
  select table_id, product_id, min(ctid) as keeper, sum(quantity) as total_quantity
  from public.orders
  group by table_id, product_id
  having count(*) > 1
), updated as (
  update public.orders o
  set quantity = d.total_quantity
  from duplicate_groups d
  where o.ctid = d.keeper
  returning o.ctid
)
delete from public.orders o
using duplicate_groups d
where o.table_id = d.table_id
  and o.product_id = d.product_id
  and o.ctid <> d.keeper;

create unique index if not exists orders_one_product_per_table
  on public.orders (table_id, product_id);

create or replace function public.save_table_order(
  p_table_id text,
  p_expected_version bigint,
  p_table jsonb,
  p_items jsonb
)
returns jsonb
language plpgsql
as $$
declare
  v_table public.tables%rowtype;
begin
  -- This also supports a locally created table being synchronized after reconnect.
  insert into public.tables (
    id, name, status, customer_name, assigned_waiter_id, created_at,
    is_bar_account, order_version
  ) values (
    p_table_id,
    coalesce(p_table->>'name', 'Mesa'),
    coalesce(p_table->>'status', 'ocupada'),
    coalesce(p_table->>'customer_name', ''),
    nullif(p_table->>'assigned_waiter_id', '')::uuid,
    coalesce(nullif(p_table->>'created_at', '')::timestamptz, now()),
    coalesce((p_table->>'is_bar_account')::boolean, false),
    0
  ) on conflict (id) do nothing;

  select * into v_table
  from public.tables
  where id = p_table_id
  for update;

  if p_expected_version is null or v_table.order_version <> p_expected_version then
    raise exception 'TABLE_ORDER_CONFLICT'
      using errcode = '40001',
            detail = format('Expected version %s but current version is %s', p_expected_version, v_table.order_version);
  end if;

  update public.tables
  set name = coalesce(p_table->>'name', v_table.name),
      status = coalesce(p_table->>'status', v_table.status),
      customer_name = coalesce(p_table->>'customer_name', v_table.customer_name),
      assigned_waiter_id = coalesce(nullif(p_table->>'assigned_waiter_id', '')::uuid, v_table.assigned_waiter_id),
      is_bar_account = coalesce((p_table->>'is_bar_account')::boolean, v_table.is_bar_account),
      order_version = v_table.order_version + 1
  where id = p_table_id;

  delete from public.orders where table_id = p_table_id;

  insert into public.orders (table_id, product_id, quantity, is_printed)
  select
    p_table_id,
    (item->>'product_id')::uuid,
    (item->>'quantity')::numeric,
    coalesce((item->>'is_printed')::boolean, true)
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb)) as item;

  return jsonb_build_object('order_version', v_table.order_version + 1);
end;
$$;

-- The application currently authenticates users in its own users table rather
-- than Supabase Auth. Keep existing table/RLS policy decisions intact and grant
-- execution only to the same API roles already used by the client.
grant execute on function public.save_table_order(text, bigint, jsonb, jsonb) to anon, authenticated;
